insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_FROM_COMPLAINT','Email for send mail specific complaint','albertopaico10@gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_FROM_CREATION_USER','Email for send mail specific creation user','albertopaico10@gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','PASSWORD_FROM','Password for send mail','Pa55w0rd4097',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','SUBJECT_CREATION_USER','Subject Creation User for send mail','InMobile - Creation User',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','SUBJECT_COMPLETE_COMPLAINT','Sbject Complete Complaint for send mail','InMobile - Registro Denuncia',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_TRUE','Configuration Email ','true',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_SMTP_GMAIL','Configuration Value for Send Email SMTP','smtp.gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_SMTP_OJOVIAL','Configuration Value for Send Email OJO VIAL SMTP','smtp.gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_PORT_OJOVIAL','Configuration Value for Send Email OJO VIAL PORT','25',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_PORT_GMAIL','Configuration Value for Send Email PORT','25',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_CREATION_USER','Texto para enviar en el correo','<html><body><p><b>InMobile Bienvenido - Test Email</b></p><br/><p>Estimo Usario:</p><br/><p>Se le agradece haber elegido la aplicaci?n</p><p>Su cuenta ha sido creada con exito</p><p><b>Gracias</b></p></body></html>',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_COMPLETE_COMPLAINT','Texto para enviar en el correo de Denuncia Registrada','<html><body><p><b>InMobile Generacion de Denuncia - Test Email</b></p><br/><p>Estimo Usario:</p><br/><p>Se le agradece haber elegido la aplicación</p><p>Su denuncia fue registrada con exito, aqui el detalle : </p><p><b>Id Denuncia : </b>${idComplaint}</p><p><b>Lugar de la Infracción : </b>${address}</p><p><b>Placa del Vehiculo : </b>${numberPlate}</p><p><b>Estados de Denuncia : ABIERTA</b></p><p>Le estaremos informando del proceso de esta denuncia</p><p><b>Gracias</b></p></body></html>',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','TRANSPORT_PROTOCOL_OJOVIAL','Configuration Value for Transport Protocol OJO VIAL','smtp',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_FROM_COMPLAINT_GMAIL','Email for send mail specific complaint','albertopaico10@gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_FROM_CREATION_USER_GMAIL','Email for send mail specific creation user - GMAIL','albertopaico10@gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','PASSWORD_FROM_GMAIL','Password for send mail','Pa55w0rd4097',1);

select * from tb_system_param where generalParam='EMAIL';